db:
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  database: "short_url"
  tablePrefix: ""                 # 表名前缀（用于分表场景）
  enableDBInit: true              # 是否在启动时自动初始化数据库结构
  slowThreshold: 200000000       # 慢查询阈值（200毫秒）
  skipDefaultTransaction: false   # 是否跳过默认事务
redis:
  host: "localhost"
  port: 6379
  prefix: "short_url"            # Key前缀（环境隔离）
  expiration: 86400              # 默认缓存时间（24小时）
  poolSize: 1000                 # 连接池最大连接数
  minIdleConns: 100              # 最小空闲连接
  maxIdleConns: 500              # 最大空闲连接
  dialTimeout: 5000              # 连接超时（5秒）
  readTimeout: 2000              # 读超时（2秒）
  writeTimeout: 2000             # 写超时（2秒）
lru:
  size: 500000                   # 固定缓存条目数
  percentage: 3                  # 内存占比（备用）
  expiration: 28800              # 缓存过期时间（8小时）
bloom_filter:
  m: 1000000                     # 位数组大小（约100万个元素）
  k: 7                           # 哈希函数数量
  key: "short_url_bloom_filter"  # Redis中的key名称
log:
  mode: "dev"                   # 生产模式
  outputPaths:
    - "./log/log.txt"            # 常规日志路径
  errorOutputPaths:
    - "./log/error_output.txt"   # 错误日志路径
short_url:
  suffix: "_LWH"          # 短链后缀
  weights: [1009, 1231, 1031, 1013, 1019, 1021] # 哈希权重
job:
  timeout: 30                     # 任务超时时间（秒）
  expr: "0 0 4 * * *"             # 每天凌晨4点执行
  enabled: true                   # 任务开关
grpc:
  server:
    port: 0                       # 自动分配端口
    etcdTTL: 60                    # 服务注册TTL（秒）
    etcdAddr: "127.0.0.1:22380"      # etcd地址
etcd:
  endpoints:
    - "127.0.0.1:22380"            # etcd集群节点