app:
  addr: ":8080"

log:
  mode: "prod"
  outputPaths:
    - "./log/log.txt"
  errorOutputPaths:
    - "./log/error_output.txt"

etcd:
  addrs:
    - "localhost:22382"

grpc:
  client:
    shortUrl:
      target: "etcd:///service/short_url"
      Secure: false
  
short_url:
  weights: [1009, 1231, 1031, 1013, 1019, 1021]


rate_limit:
  rate: 1ms                    # 令牌生成速率（1ms一个令牌 = 1000 QPS）
  capacity: 10000               # 桶容量（10000个令牌，大容量）
  expire: 10m                   # key过期时间（10分钟）
  prefix: "rate_limit"          # 限流器key前缀

hystrix:
  Timeout:                10000
  MaxConcurrentRequests:  2000
  SleepWindow:            2000
  RequestVolumeThreshold: 1000
  ErrorPercentThreshold:  50