// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"short_url/web/ioc"
	"short_url/web/routes"
)

// Injectors from wire.go:

func Init() *gin.Engine {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	rateLimiter, _ := ioc.InitRateLimiter(cmdable)
	v := ioc.InitGinMiddleware(logger, rateLimiter)
	client := ioc.InitEtcdClient()
	shortUrlServiceClient := ioc.InitShortUrlClient(client)
	apiHandler := routes.NewApiHandler(shortUrlServiceClient)
	serverHandler := ioc.InitServerHandler(shortUrlServiceClient)
	string2 := ioc.InitHystrix()
	healthHandler := routes.NewHealthHandler(string2)
	engine := ioc.InitWebServer(v, apiHandler, serverHandler, healthHandler)

	return engine
}
