// Code generated by Wire. DO NOT EDIT.


package main

import (
	"github.com/gin-gonic/gin"
	"short_url_rpc_study/web/ioc"
	"short_url_rpc_study/web/routes"
)

// Injectors from wire.go:

func Init() *gin.Engine {
	logger := ioc.InitLogger()
	v := ioc.InitGinMiddleware(logger)
	client := ioc.InitEtcdClient()
	shortUrlServiceClient := ioc.InitShortUrlClient(client)
	apiHandler := routes.NewApiHandler(shortUrlServiceClient)
	serverHandler := ioc.InitServerHandler(shortUrlServiceClient)
	engine := ioc.InitWebServer(v, apiHandler, serverHandler)
	return engine
}
