// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"short_url_rpc_study/web/ioc"
	"short_url_rpc_study/web/routes"
)

// Injectors from wire.go:

func Init() (*App, error) {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	rateLimiter, err := ioc.InitRateLimiter(cmdable)
	if err != nil {
		return nil, err
	}
	v := ioc.InitGinMiddleware(logger, rateLimiter)
	client := ioc.InitEtcdClient()
	shortUrlServiceClient := ioc.InitShortUrlClient(client)
	apiHandler := routes.NewApiHandler(shortUrlServiceClient)
	serverHandler := ioc.InitServerHandler(shortUrlServiceClient)
	string2 := ioc.InitHystrix()
	healthHandler := routes.NewHealthHandler(string2)
	engine := ioc.InitWebServer(v, apiHandler, serverHandler, healthHandler)
	app := &App{
		Engine: engine,
	}
	return app, nil
}
